# Generated by Django 5.2 on 2025-04-25 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', 'ensure_appsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='State Name')),
                ('name_ar', models.CharField(max_length=300, verbose_name='Arabic State Name')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
            },
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='organization_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Organization Logo'),
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Municipality Name')),
                ('name_ar', models.CharField(max_length=300, verbose_name='Arabic Municipality Name')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipalities', to='Core.state', verbose_name='State')),
            ],
            options={
                'verbose_name': 'Municipality',
                'verbose_name_plural': 'Municipalities',
            },
        ),
    ]
