# Generated by Django 5.2 on 2025-04-26 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Course Code')),
                ('name', models.CharField(max_length=300, verbose_name='Course Name')),
                ('name_ar', models.CharField(max_length=300, verbose_name='Arabic Course Name')),
                ('duration', models.IntegerField(verbose_name='Duration (hours)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='Course Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Course Type Name')),
                ('name_ar', models.CharField(max_length=300, verbose_name='Arabic Course Type Name')),
            ],
            options={
                'verbose_name': 'Course Type',
                'verbose_name_plural': 'Course Types',
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Profession Name')),
                ('name_ar', models.CharField(max_length=300, verbose_name='Arabic Profession Name')),
                ('fee_value', models.FloatField(verbose_name='Fee Value')),
            ],
            options={
                'verbose_name': 'Profession',
                'verbose_name_plural': 'Professions',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Session Code')),
                ('name', models.CharField(max_length=100, verbose_name='Session Name')),
                ('name_ar', models.CharField(max_length=100, verbose_name='Arabic Session Name')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='State Name')),
                ('name_ar', models.CharField(max_length=300, verbose_name='Arabic State Name')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
            },
        ),
        migrations.CreateModel(
            name='CourseLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Level Name')),
                ('name_ar', models.CharField(max_length=300, verbose_name='Arabic Level Name')),
                ('duration', models.IntegerField(verbose_name='Duration (hours)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='Core.course', verbose_name='Course')),
                ('next_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_levels', to='Core.courselevel', verbose_name='Next Level')),
            ],
            options={
                'verbose_name': 'Course Level',
                'verbose_name_plural': 'Course Levels',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='Core.coursetype', verbose_name='Course Type'),
        ),
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(default='Ceilgest', max_length=100, verbose_name='Organization Name')),
                ('organization_logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Organization Logo')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('tel', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telephone')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('website', models.CharField(blank=True, max_length=100, null=True, verbose_name='Website')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook')),
                ('twitter', models.CharField(blank=True, max_length=100, null=True, verbose_name='Twitter')),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True, verbose_name='LinkedIn')),
                ('youtube', models.CharField(blank=True, max_length=100, null=True, verbose_name='YouTube')),
                ('registration_opened', models.BooleanField(default=False, verbose_name='Registration Opened')),
                ('terms_and_conditions', models.TextField(blank=True, null=True, verbose_name='Terms and Conditions')),
                ('current_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_settings', to='Core.session', verbose_name='Current Session')),
            ],
            options={
                'verbose_name': 'Application Settings',
                'verbose_name_plural': 'Application Settings',
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Municipality Name')),
                ('name_ar', models.CharField(max_length=300, verbose_name='Arabic Municipality Name')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipalities', to='Core.state', verbose_name='State')),
            ],
            options={
                'verbose_name': 'Municipality',
                'verbose_name_plural': 'Municipalities',
            },
        ),
    ]
