# Generated by Django 5.2 on 2025-04-24 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(default='Ceilgest', max_length=100, verbose_name='Organization Name')),
                ('organization_logo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Organization Logo')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('tel', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telephone')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('website', models.CharField(blank=True, max_length=100, null=True, verbose_name='Website')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook')),
                ('twitter', models.CharField(blank=True, max_length=100, null=True, verbose_name='Twitter')),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True, verbose_name='LinkedIn')),
                ('youtube', models.CharField(blank=True, max_length=100, null=True, verbose_name='YouTube')),
                ('registration_opened', models.BooleanField(default=False, verbose_name='Registration Opened')),
                ('terms_and_conditions', models.TextField(blank=True, null=True, verbose_name='Terms and Conditions')),
                ('current_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_settings', to='Core.session', verbose_name='Current Session')),
            ],
            options={
                'verbose_name': 'Application Settings',
                'verbose_name_plural': 'Application Settings',
            },
        ),
    ]
