# Generated by Django 5.2 on 2025-04-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_state_alter_appsettings_organization_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Profession Name')),
                ('name_ar', models.CharField(max_length=300, verbose_name='Arabic Profession Name')),
                ('fee_value', models.FloatField(verbose_name='Fee Value')),
            ],
            options={
                'verbose_name': 'Profession',
                'verbose_name_plural': 'Professions',
            },
        ),
    ]
