# Generated by Django 5.2 on 2025-04-25 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Course Type Name')),
                ('name_ar', models.CharField(max_length=300, verbose_name='Arabic Course Type Name')),
            ],
            options={
                'verbose_name': 'Course Type',
                'verbose_name_plural': 'Course Types',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Course Code')),
                ('name', models.CharField(max_length=300, verbose_name='Course Name')),
                ('name_ar', models.CharField(max_length=300, verbose_name='Arabic Course Name')),
                ('duration', models.IntegerField(verbose_name='Duration (hours)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='Course Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('course_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='Core.coursetype', verbose_name='Course Type')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
    ]
