# Generated by Django 5.2 on 2025-04-26 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_coursetype_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Level Name')),
                ('name_ar', models.CharField(max_length=300, verbose_name='Arabic Level Name')),
                ('duration', models.IntegerField(verbose_name='Duration (hours)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='Core.course', verbose_name='Course')),
                ('next_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_levels', to='Core.courselevel', verbose_name='Next Level')),
            ],
            options={
                'verbose_name': 'Course Level',
                'verbose_name_plural': 'Course Levels',
            },
        ),
    ]
